server:
  port: 8090

spring:
  application:
    name: analytics-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.saxion.proj: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/analytics-service.log

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: docker

logging:
  level:
    root: INFO
