# Analytics Service CI/CD - Complete Configuration

variables:
  SERVICE_NAME: "analytics-service"
  SERVICE_PORT: "8090"

# Build analytics service
build_analytics:
  stage: build
  script:
    - echo "Building $SERVICE_NAME..."
    - mvn clean compile -pl $SERVICE_NAME -am $MAVEN_CLI_OPTS
    - echo "✅ $SERVICE_NAME build completed"
  rules:
    - if: '$CI_COMMIT_BRANCH == "TFMS_dev_v1.0.0"'
      changes:
        - "analytics-service/**/*"
    - if: '$CI_COMMIT_BRANCH == "TFMS_v1.0.0_dev"'
      changes:
        - "analytics-service/**/*"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "analytics-service/**/*"

# Package analytics service  
package_analytics:
  stage: package
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache maven openjdk17
    - echo "Preparing to package $SERVICE_NAME..."
  script:
    - echo "Packaging $SERVICE_NAME with Maven..."
    - mvn package -DskipTests -pl $SERVICE_NAME -am $MAVEN_CLI_OPTS
    - echo "Building Docker image for $SERVICE_NAME..."
    # Build Docker image
    - cd analytics-service
    - docker build -t $SERVICE_NAME:$CI_COMMIT_SHA .
    - docker tag $SERVICE_NAME:$CI_COMMIT_SHA $SERVICE_NAME:latest
    - echo "✅ Successfully built $SERVICE_NAME Docker image"
  rules:
    - if: '$CI_COMMIT_BRANCH == "TFMS_dev_v1.0.0"'
      changes:
        - "analytics-service/**/*"
    - if: '$CI_COMMIT_BRANCH == "TFMS_v1.0.0_dev"'
      changes:
        - "analytics-service/**/*"
  artifacts:
    expire_in: 1 week
    paths:
      - "analytics-service/target/*.jar"

# Deploy analytics service (skeleton - to be expanded later)
deploy_analytics:
  stage: deploy
  script:
    - echo "Deployment placeholder for $SERVICE_NAME"
    - echo "Docker image tagged as $SERVICE_NAME:latest"
    - echo "Ready for deployment configuration"
  rules:
    - if: '$CI_COMMIT_BRANCH == "TFMS_dev_v1.0.0"'
      changes:
        - "analytics-service/**/*"
      when: manual
    - if: '$CI_COMMIT_BRANCH == "TFMS_v1.0.0_dev"'
      changes:
        - "analytics-service/**/*"
      when: manual
  dependencies:
    - package_analytics

# Test analytics service
test_analytics:
  stage: test
  script:
    - echo "Running tests for $SERVICE_NAME..."
    - mvn test -pl $SERVICE_NAME $MAVEN_CLI_OPTS
    - echo "✅ $SERVICE_NAME tests completed"
  rules:
    - if: '$CI_COMMIT_BRANCH == "TFMS_dev_v1.0.0"'
      changes:
        - "analytics-service/**/*"
    - if: '$CI_COMMIT_BRANCH == "TFMS_v1.0.0_dev"'
      changes:
        - "analytics-service/**/*"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "analytics-service/**/*"
  dependencies:
    - build_analytics
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - "analytics-service/target/surefire-reports/TEST-*.xml"
    paths:
      - "analytics-service/target/surefire-reports/"
