version: "3.9"

services:
  analytics-service:
    build:
      context: ../../platform/monitoring/analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - tfms-network
    volumes:
      - analytics-logs:/app/logs

volumes:
  analytics-logs:
    driver: local

networks:
  tfms-network:
    driver: bridge
    name: tfms-network
